//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livre
    {
        public int id_Livre { get; set; }
        public string Nom { get; set; }
        public Nullable<int> id_Auteur { get; set; }
        public Nullable<int> id_Collection { get; set; }
        public Nullable<int> id_Dessinateur { get; set; }
    
        public virtual Auteur Auteur { get; set; }
        public virtual Auteur Auteur1 { get; set; }
        public virtual Collections Collections { get; set; }
    }
}
