//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type_Auteur
    {
        public Type_Auteur()
        {
            this.Auteur = new HashSet<Auteur>();
        }
    
        public int id_TypeAuteur { get; set; }
        public string Nom { get; set; }
    
        public virtual ICollection<Auteur> Auteur { get; set; }
    }
}
